services:
  amnezia-wg-easy:
    container_name: amnezia-wg-easy
    image: ghcr.io/wowly/amnezia-wg-easy:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${WG_PORT}:${WG_PORT}/udp"
      - "${PORT}:${PORT}/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./config:/etc/amnezia/amneziawg
